### ISSUE TITLE
from keras_tqdm import TQDMCallback

### ISSUE THREAD

**Issue by leeqiaogithub** [tfriedel/neural-image-assessment#2]
when i run train_model.py,there was an error:
No module named keras_tqdm
so I want to know what it is.

**Comment by tfriedel** [comment]
It's a library which shows nice progressbars for the Kerala training process in Jupyter. Install with pihttps://github.com/bstriner/keras-tqdm/blob/master/README.rst

**Comment by leeqiaogithub** [comment]
@tfriedel  thanks for your reply. 
there was another error:form keras import TQDMCallback -> cannot import name TQDMCallback.
I checked keras' official documentation,and did not found anything about "TQDMCallback".so I want to know how can i fix this error and whether it is related to keras' version.

**Comment by tfriedel** [comment]
No this is solved by installing keras_tqdm. It's not imported from keras but keras_tqdm

**Comment by leeqiaogithub** [comment]
> It's a library which shows nice progressbars for the Kerala training process in Jupyter. Install with pihttps://github.com/bstriner/keras-tqdm/blob/master/README.rst

oh yes,I made a mistake. thanks a lot!
